--Table for USERS 
DROP TABLE USERS;
CREATE TABLE USERS(ID INTEGER PRIMARY KEY, NAME VARCHAR(50), EMAIL VARCHAR(50), SALT VARCHAR(20), PASSWORD VARCHAR(100));

--Table for CHORES
DROP TABLE CHORES;
CREATE TABLE CHORES(ID INTEGER PRIMARY KEY, USER_ID INTEGER, CHORE VARCHAR, DESCRIPTION VARCHAR(200), FREQUENCY VARCHAR (20), DIFFICULTY INTEGER);